# This is a basic workflow to help you get started with Actions

name: GitHub Actions CI

# Controls when the actions will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: My Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: pypy:3-7.3.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs pypy version
    - name: Run pypy3 version
      run: pypy3 --version

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        MY_VAR: "Hi there! My name is"
        FIRST_NAME: "Mona"
        MIDDLE_NAME: "The"
        LAST_NAME: "Octocat"
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
        echo test, and deploy your project.
